# Auto-generated by configure. Edit if project defaults need to change.

TOP ?= ../../..

CROSS_COMPILE ?= 
CROSS ?= $(CROSS_COMPILE)
SYSROOT ?= 
CC ?= $(CROSS_COMPILE)gcc
CXX ?= $(CROSS_COMPILE)g++
LD ?= $(CROSS_COMPILE)ld
AS ?= $(CC)
AR ?= $(CROSS_COMPILE)ar
OBJCOPY ?= $(CROSS_COMPILE)objcopy
OBJDUMP ?= $(CROSS_COMPILE)objdump

MKDIR ?= mkdir
RM ?= rm -rf
RMDIR ?= rm -rf
PYTHON ?= python3

BUILD ?= build
TARGET ?= build/emtask.exe

CFLAGS += -Wno-unused-result
CXXFLAGS +=
ASFLAGS +=
LDFLAGS +=  

INC += -I. -I./$(BUILD) -I$(TOP) -I$(TOP)/target
LIB += -lws2_32 -ladvapi32
PREBUILD ?= PERBUILD

CONF_CFLAG += 
CONF_LDFLAG ?=
CONF_BUILD ?=
CONF_TARGET ?=
CONF_TOP ?=
CONF_SYSROOT ?=
CONF_LIB ?=
CONF_LIBPATH ?=
CONF_PREBUILD ?=
CONF_INCLUDE ?=

ifeq ($(DEBUG),1)
CFLAGS += -O0 -g
CXXFLAGS += -O0 -g
ASFLAGS += -O0 -g
else
CFLAGS += -Os -g
CXXFLAGS += -Os -g
ASFLAGS += -Os -g
endif

ifeq ($(PG),1)
CFLAGS += -pg
CXXFLAGS += -pg
ASFLAGS += -pg
LDFLAGS += -pg
endif
