#ifndef EMSSH_SSH_CONFIG_H
#define EMSSH_SSH_CONFIG_H

#include <stddef.h>

#define EMSSH_VERSION_MAJOR 0
#define EMSSH_VERSION_MINOR 1
#define EMSSH_VERSION_PATCH 0

#ifndef EMSSH_SOFTWARE_NAME
#define EMSSH_SOFTWARE_NAME "emsshd_0.1"
#endif

#ifndef EMSSH_MAX_SESSIONS
#define EMSSH_MAX_SESSIONS 2u
#endif

#ifndef EMSSH_MAX_CHANNELS_PER_SESSION
#define EMSSH_MAX_CHANNELS_PER_SESSION 2u
#endif

#ifndef EMSSH_MAX_PACKET_SIZE
/*
 * RFC 4253 recommends supporting packet lengths at least up to 35000 bytes.
 * Keep payload size configurable separately via EMSSH_MAX_PAYLOAD_SIZE.
 */
#define EMSSH_MAX_PACKET_SIZE 35000u
#endif

#ifndef EMSSH_MAX_PAYLOAD_SIZE
#define EMSSH_MAX_PAYLOAD_SIZE 32768u
#endif

#ifndef EMSSH_MAX_AUTH_TRIES
#define EMSSH_MAX_AUTH_TRIES 3u
#endif

#ifndef EMSSH_SFTP_MAX_HANDLES
#define EMSSH_SFTP_MAX_HANDLES 16u
#endif

#ifndef EMSSH_USE_DYNAMIC_ALLOC
#define EMSSH_USE_DYNAMIC_ALLOC 0
#endif

#define EMSSH_IDENTIFICATION_PREFIX "SSH-2.0-"
#define EMSSH_IDENTIFICATION_LINE EMSSH_IDENTIFICATION_PREFIX EMSSH_SOFTWARE_NAME

#endif
