
#ifndef MBEDTLS_MBEDTLS_CONFIG_H
#define MBEDTLS_MBEDTLS_CONFIG_H

#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_SHA256_SMALLER
#define MBEDTLS_SSL_PROTO_TLS1
#define MBEDTLS_SSL_PROTO_TLS1_1
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_PROTO_TLS1_3
#define MBEDTLS_SSL_SERVER_NAME_INDICATION

// Lowering this may force fragmentation and break tests, even if runtime still works.
// #define MBEDTLS_SSL_MAX_CONTENT_LEN (16384)
// #define MBEDTLS_SSL_IN_CONTENT_LEN (MBEDTLS_SSL_MAX_CONTENT_LEN)
// #define MBEDTLS_SSL_OUT_CONTENT_LEN (4096)  

#define MBEDTLS_BASE64_C
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ERROR_C
#define MBEDTLS_GCM_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD5_C
#define MBEDTLS_OID_C
#define MBEDTLS_PKCS5_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA224_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA384_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_SSL_CLI_C // Enable SSL client.
#define MBEDTLS_SSL_SRV_C // Enable SSL server.
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_PEM_PARSE_C // Enable common PEM certificate parsing.
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_USE_C


#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_TEST_SW_INET_PTON
#define MBEDTLS_PLATFORM_C

#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_HKDF_C
#define MBEDTLS_SSL_SESSION_TICKETS
#define MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#define MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE // Enable compatibility mode; some clients require it.

// TLS cipher suites.
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#define MBEDTLS_CAN_ECDH
#define MBEDTLS_PK_CAN_ECDSA_SIGN

// Common certificate signature algorithms.
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_PKCS1_V21

#endif

// Porting layer.
#define MBEDTLS_TIMING_C
#define MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME_DATE
// #define MBEDTLS_NET_C

#define MBEDTLS_ENTROPY_HARDWARE_ALT

#endif
